/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package zettai

import org.http4k.core.HttpHandler
import org.http4k.core.Response
import org.http4k.core.Status
import org.http4k.server.asServer
import org.http4k.server.Jetty

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

val htmlPage = """
<html><body><h1 style="text-align: center; font-size: 3em;">Hello Functional World!</h1></body></html>
"""

val handler: HttpHandler = {
    Response(Status.OK).body(htmlPage)
}

fun main() {
    handler.asServer(Jetty(8080)).start()
}
