/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package zettai

import org.http4k.core.HttpHandler
import org.http4k.core.Response
import org.http4k.core.Request
import org.http4k.core.Status
import org.http4k.core.Method.GET
import org.http4k.core.Method.POST
import org.http4k.core.Status.Companion.OK
import org.http4k.core.Status.Companion.CREATED
import org.http4k.server.asServer
import org.http4k.server.Jetty
import org.http4k.routing.routes
import org.http4k.routing.bind

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

val htmlPage = """
<html><body><h1 style="text-align: center; font-size: 3em;">Hello Functional World!</h1></body></html>
"""

val app: HttpHandler = routes(
    "/greetings" bind GET to ::greetings,
    "/post" bind POST to ::receiveData
)

fun greetings(_req: Request): Response = 
  Response(OK).body(htmlPage)

fun receiveData(req: Request): Response = Response(CREATED)
  .body("Received ${req.bodyString()}")

fun main() {
    app.asServer(Jetty(8080)).start()
}
